version: '3'
services:
  manager-nginx:
    build:
      context: manager/docker/development
      dockerfile: manager/docker/development/nginx.docker
    volumes:
      - ./manager:/app
    depends_on:
      - manager-php-fpm
    ports:
      - "8080:80"
  manager-php-fpm:
    build:
      context: manager/docker/development
      dockerfile: manager/docker/development/php-fpm.docker
    volumes:
      - ./manager:/app
  manager-php-cli:
    build:
      context: manager/docker/development
      dockerfile: manager/docker/development/php-cli.docker
    volumes:
      - ./manager:/app